spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zero_order?useSSL=false&useUnicode-true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zerobase

  redis:
    port: 6379
    host: localhost
